### ISSUE TITLE
Change Back Ground Color

### ISSUE THREAD

**Issue by ghost** [CherryFramework/cherry-mega-menu#1]
Hi

How do I change the back ground color of a drop down menu?

Thanks
Will

**Comment by ghost** [comment]
You need to change the `background` property of `.cherry-mega-menu-sub` in your css file:

``` css
.cherry-mega-menu-sub {
    background: #fcfcfc;
}
```
